const Routes = {
  SPLASH_SCREEN: 'SPLASH',
  FIRST_SCREEN: 'FIRST_SCREEN',
  LOGIN_SCREEN: 'LOGIN_SCREEN',
  REGISTER_SCREEN: 'REGISTER_SCREEN',
  LOGOUT_SCREEN: 'LOGOUT_SCREEN',
  HOME_SCREEN: 'HOME_SCREEN',
  FORGOT_PASS_SCREEN: 'FORGOT_PASS_SCREEN',
  OTP_SCREEN: 'OTP_SCREEN',
  RESET_PASSWORD_SCREEN: 'RESET_PASSWORD_SCREEN',
  CONGRATULATION_SCREEN: 'CONGRATULATION_SCREEN',
};

export default Routes;
